### ISSUE TITLE
Create plexus-interop-desktop-api repository and transfer client-api.ts from finos-plexus.github.io

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#174]
### Description

The following tasks have been outlined to create a `Plexus Interop Desktop API` project repository following the conversation with @kryusvy by @mcleo-d in the Plexus Interop API project meeting on 15th May 2020.

These work items are also outlined on https://github.com/finos/finos-pmcs/issues/32

### Tasks
- [x] Create `plexus-interop-desktop-api` repository in the [FINOS organisation](https://github.com/finos) on GitHub
- [x] Transfer [client-api.ts](https://github.com/finos-plexus/finos-plexus.github.io/blob/master/client-api/client-api.ts) from `finos-plexus.github.io` into `plexus-interop-api` alongside the FINOS `Project Blueprint` template
- [x] Delete folder https://github.com/finos-plexus/finos-plexus.github.io/blob/master/client-api/ from `finos-plexus.github.io`

**Comment by mcleo-d** [comment]
The following is an update of this issue.

- [plexus-interop-desktop-api](https://github.com/finos/plexus-interop-desktop-api) has been created in the [FINOS organisation](https://github.com/finos) on GitHub. 
- FINOS `Project Blueprint` has been merged into the [plexus-interop-desktop-api](https://github.com/finos/plexus-interop-desktop-api) repository as a project boilerplate.
- [client-api.ts](https://github.com/finos-plexus/finos-plexus.github.io/blob/master/client-api/client-api.ts) has been transferred into the [src](https://github.com/finos/plexus-interop-desktop-api/tree/master/src) folder of [plexus-interop-desktop-api](https://github.com/finos/plexus-interop-desktop-api) 
- PR https://github.com/finos-plexus/finos-plexus.github.io/pull/32 has been created to **Delete client-api.ts** from the original file repository and assigned to @udalmik and @kryusvy for review and merge.

**Comment by maoo** [comment]
All done here, TY @udalmik @kryusvy !

Closing issue, /cc @mcleo-d
